name: chatbot

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: chatbot-backend:latest
    container_name: chatbot-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_API_URL: ${OPENAI_API_URL:-https://api.openai.com/v1/chat/completions}
      OPENAI_MODEL: ${OPENAI_MODEL:-gpt-3.5-turbo}
      OPENAI_SYSTEM_PROMPT: ${OPENAI_SYSTEM_PROMPT:-}
      APP_CORS_ALLOWED_ORIGINS: ${APP_CORS_ALLOWED_ORIGINS:-https://staging.d2y4knmwkrsavb.amplifyapp.com}
    restart: unless-stopped
